language: node_js
cache: 
directories:
- node_modules
notifications: 
email: false
branches: 
except:
- "/^v\\d+\\.\\d+\\.\\d+$/"
env:
  global:
  - secure: CUZ0thgBc640jAqTQwfi7MKio2EpoxBDpnHt3smv1Dj3ivl0WBsaauy/aQ0MY43xX4jz9K3KV3rQvXXk6PXWudZSZ2YmIAORIEaWeKwcpf3DWNh8lFN6/5JgCunj8Fx+QbLAA2556pI1lZOAVlEUlub52szRF4EWRnOZYtgzKhNTg+APTFJXXtWI1R5/dob9Rbst5MeF57QkiglIr69bXl36VN+rJ81/vDVyRUG/Uud24YlJLAl8Efoj75jpjU9dEdGIqWI2TlEHSrKSDFKT6Etfk0ZwhJgqDe6MvKd7DPwqjAgL4rcW9P6hpQxu1Edgjw8nmsguPpcKv7aiFJWYsFzW+SmfDe9nAnxZX82e1HySYNoqyLzTeQVsH+dOcycqkWxK6xGhlQ18Bbp/pJ6WSePP/QkZL5rxCoMRJyLgcvQEWoYF/oyOEPb4AGooYZA7DlMXT4gGzsoSgUCWukHuAsfBAGEqStp4xZ+vx+h+2BzYsjWbFLA/A1kqMpf5S7PoXmoCw7ID/Il/ZrcmEyyz2uRFzAVS1UQZZ0t0S551vWb2Yp0RxhLHZOjvhZIaFdgNUkExLLr2dz+lZ0lBXDs8zO/i8RnIyov4UWNbBV2IYZZ6gC1wq+ffL22ZPxayeXGB2NP2D6Ax3zJQmlkStoohZ9EwLRKaeVLW4ilGGUtglO4=
  - secure: B8SuGjgsaQFO6Sj4sSwRdXhun3qzoxwqMSKJpAGGt7+YjsRMxxSXHpcTBEpDnaCqqCzsWfY+Y50+PbuMOXf3VvZwRZsibcEreznncZB/00Uj0VH7k20bjhwD1QMOIfBI2Dfg9AcaTT7xb9BNZd/AvMQnEEDiFZIFZd8GHfYEhvLUfHqbm77+lgQPpmVyIUVj2M+pBobGeZXlqMpQl+s+85+tectJhjB6cpfZe0jFHZQYlAQbH16jhv0NqC4oBNPwXWgby22E7ONirbeivmBKgBF3IN/pfO2qxAhLTnHK9liFQC9vcRmQHOgfbi8elHlUj8VGVvsNMzP57iKG7UsMjAs2N64FE+5ai8r793bfFTfpZIrV9diFJt+PmHkvAUx18Aj0dHF3E3eEU0OGjQ6uPycMXlZDKwwMNBJA3F/ogrFr1f5+l7VIfvToccT858JFFe6HQfHqb8HTS7ZLv2Mf/1hxyqiicfnNmptkJSkm46maDll2EwnW8iTcB9T2p4z8BMt63NfX4G5qdvwZGHgAzgLjcTQkP4DHoDQrCmeVZz+slQu3PV7vdDBdFjwkGkr84vV/JsR1tzSXZxbmEyjpIbOwd+VF+YtubHUiyuuxHP2b3g9wIbnBqsdxEwkRICK6oWw41gFAD0zYaDeDh6O8Du2n+IFlbMg+gC0dy1/aTYI=
